[package]
name = "sat"
version = "0.0.2"
authors = ["michaelbeaumont <mjboamail@gmail.com>"]

[dependencies]
log="0.4.5"
env_logger="0.5.13"
glob="0.2.11"
vec_map="0.8.1"
bit-set="0.5.0"
docopt="1.0.1"
serde="1.0.80"
serde_derive="1.0.80"
